trigger:
  branches:
    include:
    - main

pool:
  name: Test-Repo-Agent-Pool

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: CMakeToolInstaller@1
      inputs:
        cmakeVersion: '3.10'
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          . ./second.ps1
          Build-Proj
