trigger:
  branches:
    include:
    - main

pool:
  name: Test-Repo-Agent-Pool

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          . ./init.ps1
          Setup-Env
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          . ./init.ps
          Build-Proj
