trigger: none

pool:
  name: Test-Repo-Agent-Pool

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          . ./init.ps1
          Setup-Env
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          . ./init.ps1
          Build-Proj

- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          . ./init.ps1
          Release-Build